config/routes.rb
Aleph::Application.routes.draw do
  
  root 'calculations#index'
  
  resources :calculations
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
    include ExpressionHelper
    def create
      @sum = calculation_params
      if @sum[:answer] == session[:missing]
        @correct = true
        response = ExpressionHelper.random_exp
        if response.include? nil
          response = ExpressionHelper.random_exp
        end
        @result = response[0]
        @missing = response[1]
        @expression = response[2]
        session[:missing] = @missing
      else
        @correct = false
        @result = session[:result]
        @missing = session[:missing]
        @expression = session[:expression]
      end
    end
    def index
      response = ExpressionHelper.random_exp
      if response.include? nil
        response = ExpressionHelper.random_exp
      end
      @result = response[0]
      @missing = response[1]
      @expression = response[2]
      session[:ugh] = response
      session[:missing] = @missing
      session[:expression] = @expression
      session[:result] = @result
    end
    private
      def calculation_params
        params.require(:calculation).permit(:answer)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
module CalculationsHelper
  def calculate
  end
end

app/helpers/expression_helper.rb
module ExpressionHelper
	def self.random_exp
    alphabet = ("a".."z").to_a
    randomLetter1 = alphabet.shuffle.sample

    randomNumber1 = 1 + rand(10)
    randomNumber2 = 1 + rand(10)
    randomNumberMystery = 1 + rand(10)
    symbolChance = 1 + rand(100)

    if (symbolChance < 40)
      symbol = "-"
      randomResult = (randomNumber1 * randomNumberMystery) - randomNumber2
    elsif (symbolChance > 40 && symbolChance < 80)
      symbol = "+"
      randomResult = (randomNumber1 * randomNumberMystery) + randomNumber2
    elsif (symbolChance > 80 && symbolChance < 90)
      symbol = "*"
      randomResult = (randomNumber1 * randomNumberMystery) * randomNumber2
    elsif (symbolChance > 90 && symbolChance < 100)
      symbol = "/"
      randomResult = (randomNumber1 * randomNumberMystery) / randomNumber2
    end
    return randomResult, randomNumberMystery.to_s, randomNumber1.to_s + randomLetter1 + " " + symbol + " " + randomNumber2.to_s + " " + "=" + " " + randomResult.to_s
	end
end

app/views/calculations/_form.html.erb
<div class="expressionText text-center"><%= @expression %></div>
<div class="bubble text-center">
	<%= form_for :calculation, url: calculations_path, remote: true do |f| %>
    <%= f.text_field :answer, placeholder: 'Think you can solve it?', class: 'form-control' %>
	  <%= f.submit 'Submit Answer', class:'btn btn-success'%>
	<% end %>
</div>

app/views/calculations/create.js.erb
var response = <%= @correct %>;
if (response == true) {
	$('.form').html("<%= j render 'form' %>")
	$('.response').html('<i class="fa fa-check" aria-hidden="true"></i>');
	$('.response').removeClass('fail').addClass('success');
	$('i').fadeOut(1500);
} else if (response == false) {
	$('.response').html('<i class="fa fa-times" aria-hidden="true"></i>');
	$('.response').removeClass('success').addClass('fail');
}

app/views/calculations/index.html.erb
<div class="response text-center"></div>
<div id="form_and_stuff text-center">
	<div class="form">
		<%= render 'form' %>
	</div>
</div>

app/views/calculations/show.html.erb
You did it!

app/views/calculations/testindex.html.erb
<div class="expressionText"><%= @expression %></div>
<div class="bubble">
	
		<%= form_tag calculations_path, :method => :post, :remote => true do %>
		<%= text_field_tag :data, nil, :onkeyup => "this.form.sub.click()" %> 
  		<%= submit_tag "submit", :name => "sub", class: 'btn btn-success' %>
   		<br>
		<div class = "sum">
   			<span id="sum"></span>
			<% if @correct %>
				<div class="great">!</div>
			<% else %>
			<% end %>
			<%= @missing %>
			<%= @correct %>
		<% end %>				
			
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aleph</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
</head>
<body>

<%= yield %>

</body>
</html>